export const CONFIG = {
  CANVAS_WIDTH: 1200,
  CANVAS_HEIGHT: 800,

  GRID_COLS: 24,
  GRID_ROWS: 16,
  TILE_SIZE: 50,

  MARBLE_COUNT: 8,
  MARBLE_RADIUS: 18,
  MARBLE_SPEED: 1.5,
  MARBLE_HEALTH: 100,

  SWORD_LENGTH: 30,
  SWORD_WIDTH: 4,
  SWORD_ORBIT_RADIUS: 40,
  SWORD_ROTATION_SPEED: 0.05,
  SWORD_DAMAGE: 25,

  KNOCKBACK_FORCE: 8,
  KNOCKBACK_DECAY: 0.9,

  CLAIM_DELAY_NEUTRAL: 0.3,
  CLAIM_DELAY_ENEMY: 0.8,
  CLAIM_RING_RADIUS: 22,
  CLAIM_RING_WIDTH: 3,
  CLAIM_PULSE_SPEED: 8,
  CLAIM_CANCEL_KNOCKBACK: 10,
  CLAIM_CONTEST_RADIUS: 30,

  COMBO_WINDOW: 1.0,
  COMBO_BASE_PITCH: 600,
  COMBO_PITCH_INCREMENT: 40,
  COMBO_MAX: 8,

  ROLE_CHOKEPOINT_RATIO: 0.4,
  SHAPE_WEIGHT_NEIGHBOR: 2.0,
  CHOKEPOINT_ENEMY_BONUS: 3.0,

  MATCH_DURATION: 90,
  ROUND_DURATION: 180,
  ROUND_INTERMISSION: 20,
  ROUND_COUNTDOWN: 3,
  SCORING: {
    giftPerCoin: 1,
    like: 0.02,
    comment: 1,
    follow: 25,
    share: 50,
    tile: 0.5,
  },

  DOMINATION_THRESHOLD: 0.65,
  ELIMINATION_ZERO_TILE_TIME: 5.0,
  DOMINATION_WARN_RATIO: 0.45,

  POWERUP_SPAWN_MIN: 8.0,
  POWERUP_SPAWN_MAX: 15.0,
  POWERUP_MAX_ON_BOARD: 3,
  POWERUP_OVERCHARGE_DURATION: 5.0,
  POWERUP_SHIELD_DURATION: 8.0,
  POWERUP_COLOR_BOMB_RADIUS: 2,
  POWERUP_TYPES: ['overcharge', 'shield', 'colorbomb'],

  CAMERA_FOCUS_LERP: 0.08,
  CINEMATIC_ZOOM: 1.8,
  CINEMATIC_FOCUS_TIME: 0.5,
  CINEMATIC_HOLD_TIME: 0.9,
  CINEMATIC_RETURN_TIME: 0.7,
  CINEMATIC_BLUR_MAX: 6,

  CAMERA_SHAKE_DEFLECT: 3,
  CAMERA_SHAKE_HIT: 6,
  CAMERA_SHAKE_KILL: 14,
  CAMERA_SHAKE_DECAY: 0.82,
  CAMERA_SHAKE_MAX_ANGLE: 0.015,

  VICTORY_PAINT_SPEED: 4,

  VIEWER_CAP: 24,
  AI_FILL_ENABLED: true,
  AI_FILL_INTERVAL: 2.0,
  NEUTRAL_COLOR: '#1a1a1a',

  WALL_COLOR: '#2a2a2e',
  WALL_HIGHLIGHT: '#3a3a3e',

  MAPS: ['Empty', 'Crossfire', 'Islands'],

  MAX_PARTICLES: 250,

  DEBUG_FPS_GRAPH_WIDTH: 120,
  DEBUG_FPS_GRAPH_HEIGHT: 40,
  DEBUG_FPS_HISTORY: 60,

  COLORS: {
    YELLOW:  '#FFD700',
    GREEN:   '#00CC44',
    ORANGE:  '#FF8C00',
    PURPLE:  '#9B30FF',
    BLUE:    '#1E90FF',
    RED:     '#FF2222',
    MAGENTA: '#FF00FF',
    CYAN:    '#00CED1',
  },

  ZONE_LAYOUT: [
    ['YELLOW',  'YELLOW',  'GREEN',   'GREEN',   'ORANGE',  'ORANGE',  'PURPLE',  'PURPLE'],
    ['YELLOW',  'YELLOW',  'GREEN',   'GREEN',   'ORANGE',  'ORANGE',  'PURPLE',  'PURPLE'],
    ['BLUE',    'BLUE',    'RED',     'RED',     'MAGENTA', 'MAGENTA', 'CYAN',    'CYAN'],
    ['BLUE',    'BLUE',    'RED',     'RED',     'MAGENTA', 'MAGENTA', 'CYAN',    'CYAN'],
  ],

  MARBLE_NAMES: ['Murienne', 'Annkott', 'Helmcas', 'Vossidy', 'Quorith', 'Daphne', 'Tybalt', 'Skorn'],
};
