export const CONFIG = {
  CANVAS_WIDTH: 1200,
  CANVAS_HEIGHT: 800,

  GRID_COLS: 48,
  GRID_ROWS: 32,
  TILE_SIZE: 25,

  MARBLE_RADIUS: 11,
  MARBLE_SPEED: 1.1,
  BALL_SPAWN_SPEED_JITTER: 0.25,
  BALL_BOUNCE_JITTER: 0.3,
  BALL_MAX_SUBSTEP: 0.4,
  BALL_OVERCHARGE_MULT: 2.2,

  SPEED_CTRL_MIN: 0.5,
  SPEED_CTRL_MAX: 3,
  SPEED_CTRL_STEP: 0.1,

  BASE_SIZE: 8,

  CAP_SCALE_MIN: 0.5,
  CAP_SCALE_MAX: 2.5,
  CAP_SCALE_STEP: 0.1,
  CAP_SCALE_DEFAULT: 1,
  BANNER_FONT_PX: 13,

  TILE_HOLD_TIME: 2.5,
  CLAIM_SFX_MIN_INTERVAL: 0.06,
  SPARK_COUNT: 2,

  OUTLINE_WIDTH: 3,
  OUTLINE_CORNER_RADIUS: 0.4,
  OUTLINE_SHIELD_DASH: [10, 7],
  OUTLINE_SHIELD_WIDTH_ADD: 2,
  CLAIM_PITCH: 720,

  MATCH_DURATION: 90,
  ROUND_DURATION: 180,
  ROUND_INTERMISSION: 20,
  ROUND_COUNTDOWN: 3,
  SCORING: {
    giftPerCoin: 1,
    like: 0.02,
    comment: 1,
    follow: 25,
    share: 50,
    tile: 0.125,
  },

  DOMINATION_THRESHOLD: 0.65,
  DOMINATION_WARN_RATIO: 0.45,

  POWERUP_SPAWN_MIN: 8.0,
  POWERUP_SPAWN_MAX: 15.0,
  POWERUP_MAX_ON_BOARD: 3,
  POWERUP_OVERCHARGE_DURATION: 6.0,
  POWERUP_COLOR_BOMB_RADIUS: 4,
  POWERUP_TYPES: ['overcharge', 'colorbomb'],
  POWERUP_FREEZE_DURATION: 4,
  POWERUP_SHIELD_DURATION: 6,
  POWERUP_MEGA_BOMB_RADIUS: 6,
  CLAIM_STORM_TILES: 48,
  SUMMON_COUNT: 3,
  EFFECT_DURATION_MAX: 30,
  EFFECT_RADIUS_MAX: 8,
  EFFECT_TILES_MAX: 200,
  EFFECT_COUNT_MAX: 8,

  GIFT_SPEED_PER_COIN: 0.05,
  GIFT_SPEED_MIN: 2,
  GIFT_SPEED_MAX: 10,

  CAMERA_FOCUS_LERP: 0.08,
  CINEMATIC_ZOOM: 1.8,
  CINEMATIC_FOCUS_TIME: 0.5,
  CINEMATIC_HOLD_TIME: 0.9,
  CINEMATIC_RETURN_TIME: 0.7,
  CINEMATIC_BLUR_MAX: 6,
  AUTOZOOM_ON_JOIN: true,
  JOIN_PROMPT_TIMEOUT: 20,
  PROMPT_BYPASS: false,
  JOIN_GUIDE_SHARE: 0.5,
  JOIN_GUIDE_TIME: 10,
  TIP_TIME: 6,
  TIP_FINAL_TIME: 30,

  CAMERA_SHAKE_KILL: 14,
  CAMERA_SHAKE_DECAY: 0.82,
  CAMERA_SHAKE_MAX_ANGLE: 0.015,

  VICTORY_PAINT_SPEED: 4,
  WIN_CONFETTI_MAX: 240,
  WIN_CONFETTI_TIME: 10,
  WIN_CONFETTI_GRAVITY: 260,
  WIN_MEDALLION_REVEAL: 0.45,
  WIN_PODIUM_DELAY: 0.9,

  VIEWER_CAP: 24,
  AI_FILL_ENABLED: true,
  AI_FILL_INTERVAL: 2.0,
  NEUTRAL_COLOR: '#1a1a1a',

  OVERLAY_BROADCAST_INTERVAL: 0.25,
  TEAMS_AUTOSAVE_MS: 1500,

  WALL_COLOR: '#2a2a2e',
  WALL_HIGHLIGHT: '#3a3a3e',

  MAPS: ['Empty', 'Crossfire', 'Islands'],

  MAX_PARTICLES: 250,

  COLORS: {
    YELLOW:  '#FFD700',
    GREEN:   '#00CC44',
    ORANGE:  '#FF8C00',
    PURPLE:  '#9B30FF',
    BLUE:    '#1E90FF',
    RED:     '#FF2222',
    MAGENTA: '#FF00FF',
    CYAN:    '#00CED1',
  },

  TEAM_COLORS: ['#FFD700', '#00CC44', '#FF8C00', '#9B30FF', '#1E90FF', '#FF2222', '#FF00FF', '#00CED1'],

  MARBLE_NAMES: ['Murienne', 'Annkott', 'Helmcas', 'Vossidy', 'Quorith', 'Daphne', 'Tybalt', 'Skorn'],
};
